export enum TipoRelatorio {

    TODOS_CLIENTES,
    CLIENTES_POR_PERIODO,
    TODOS_FORNECEDORES,
    TODAS_DESPESAS,
    DESPESAS_PAGAS,
    DESPESAS_VENCIDAS,
    TODOS_PRODUTOS,
    PRODUTOS_ESTOQUE_BAIXO,
    TODOS_PEDIDOS
}